### ISSUE TITLE
product_id: 11 Plese make an issue on git with this product id

### ISSUE THREAD

**Issue by MikeTheTux** [MeisterTR/ioBroker.landroid-s#15]
I have a landroid m, WG796E.1 using the latest cloud based software.
Is that supported as well?

**Comment by MeisterTR** [comment]
All devices with cloud access are supported. If you get the id warning you
are not using the newest version l. So please update to the latest version.

Am Mi., 7. Nov. 2018, 21:46 hat MikeTheTux <notifications@github.com>
geschrieben:

**Comment by MikeTheTux** [comment]
I'm using weweave/landroid-bridge. maybe it's still using an older version of ioBroker.landroid-s :-?

To get it runnung i needed to add a ...
25: "DB510",
... line into landroid-cloud-2.js

Thanks allot for the great tool!
