### ISSUE TITLE
Akkustand falsch?

### ISSUE THREAD

**Issue by darkbrain85** [MeisterTR/ioBroker.landroid-s#18]
Der Akkustand wird mir gerade vom Adapter mit 84% gemeldet. Die App zeigt mir allerdings 90%. 
Habe ich was überlesen, oder gibt es da einen "Käfer"?

Firmware 3.45 mit WR105. Unbenutzt aus dem Karton ;-) 

Edit: Ok, jetzt habe ich im Forum eine Aussagen dazu gefunden. 
[
https://forum.iobroker.net/post/177295](url)
Was heisst denn hier "Benutzerfreundlich"? Der Akkustand im Adapter ist korrekt, und die App hat "geschönte" Werte? Welcher ist denn nun relevant wenn es darum geht wann der Mäher keinen Saft mehr hat?

**Comment by MeisterTR** [comment]
Bei der Aktuellen App sollte es mit iobroker übereinstimmen hier kommen die Unterschiede meistens von unterschiedlichen abfrage Zeiten (iobbroker aktualisiert nur alle 10 min) . Wenn der Akkustand in der app jetzt abgefragt wird, kann der in iobroker schon 8 Minuten alt sein.
In der Alten App gab es nur eine Batterie Grafik die den Akkustand angezeigt hat und die stand schon bei 70 Prozent auf voll.

**Comment by darkbrain85** [comment]
Danke für die Rückmeldung! 
Allerdings werden doch Dinge wie Zeitpläne auch sofort bei Aktualisierung aus der App in Biobroker übernommen. Der Akkustand wird dann nicht übertragen?

**Comment by MeisterTR** [comment]
werden daten in der app geändert wird ein trigger ausgelößt wodurch alle daten in iobroker aktualisiert werden. der Unterschied des akkustandes kann ein umrechnungsfehler in der app sein. Die Daten in iobroker sind auf jedenfall die rohdaten die vom Roboter gesendet werden.
