### ISSUE TITLE
Status "Zurück zur Basis"

### ISSUE THREAD

**Issue by darkbrain85** [MeisterTR/ioBroker.landroid-s#19]
Mein Landroid S zeigt mir beim Rückweg zur Basis als Status "30". Dies scheint im Adapter nicht berücksichtigt zu sein. 

Datenpunkt:
landroid-s.0.mower.status

**Comment by darkbrain85** [comment]
Status 32 "Border Cut" fehlt ebenfalls... 

Bin ich der erste dem das auffällt?

**Comment by MeisterTR** [comment]
zurück zur Basis ist drin:
https://github.com/MeisterTR/ioBroker.landroid-s/blob/master/main.js#L415

32 hab ich hinzugefügt, damke

**Comment by DrCache1976** [comment]
33 ist die Zonenanfahrt.
