### ISSUE TITLE
Error Status 17

### ISSUE THREAD

**Issue by aquapro** [MeisterTR/ioBroker.landroid-s#21]
Hi,

mower.error 17 "Battery over temperature"

In meinem Fall war die Außentemperatur zu tief. Um die 0 Grad meckert der Mäher mit dem Status 17 und dem Text oben. 17 fehlt noch im Adapter. In dem Zustand läd der Mäher nicht mehr. Am Mäher wird dann -E 7- angezeigt. Auch wenn man den Mäher ausschaltet, Akku entnimmt, Normaltemperatur herstellt. Dann den Akku wieder einbaut und anschalten, kommt der Fehler immer noch am Mäher, aber er läd dann schon wieder. Man muss den Fehler am Mäher wegdrücken. Akku im Mäher lassen und auf bessere Temperatur warten hilft also nicht.

Worx Landroid M500 WR141E, also Modell 2019.

Gruß
Tino

**Comment by MeisterTR** [comment]
danke werde ich mit reinnehmen
