### ISSUE TITLE
Modell: Landroid S not supported yet. Please contact developer

### ISSUE THREAD

**Issue by jens-maus** [MeisterTR/ioBroker.landroid-s#3]
Since update of the adapter to version 2.2.0 I get the following error on starting the landroid-s adapter:

```
landroid-s.0	2018-07-17 18:35:22.442	error	Modell: Landroid S not supported yet. Please contact developer
```

If I change the name of my mower in the landroid app to "Test" then I get

```
landroid-s.0	2018-07-17 18:36:22.446	error	Modell: Test not supported yet. Please contact developer
```

My Landroid model is "Landroid S WR103SI"

**Comment by MeisterTR** [comment]
it was a little bug, i thought all S modells have the same product id, it is not. 2.2.1 should work again. now should come a warning with the product id, it would be nice if you post them.

**Comment by jens-maus** [comment]
This is the output in 2.2.1:

```
landroid-s.0	2018-07-17 19:04:04.694	warn	product_id: 35 Plese make an issue on git with this product id
```

**Comment by jens-maus** [comment]
However, event thought you adapted the output, the adapter still doesn't start because you forgot to remove the return statement :) see https://github.com/MeisterTR/ioBroker.landroid-s/commit/0b6cbaa6acfe19ea2ebc3cdecc8f6c2ed26e466d#diff-dc48ef1796bbd42b775eea5e5165534cR110

**Comment by jens-maus** [comment]
Sorry, but I just tried 2.2.2 today and the adapter is still not running with my landroid-s anymore. The messages in ioBroker are:

```
landroid-s.0	2018-07-18 21:44:42.038	warn	product_id: 35 Plese make an issue on git with this product id
landroid-s.0	2018-07-18 21:44:42.038	info	undefined
landroid-s.0	2018-07-18 21:44:42.037	info	mower 0 selected
landroid-s.0	2018-07-18 21:44:41.500	info	Logged in as XXX@YYYYY API Token Set to : ZZZZZZ
landroid-s.0	2018-07-18 21:44:41.095	info	starting. Version 2.2.2 in /opt/iobroker/node_modules/iobroker.landroid-s, node: v8.11.3
landroid-s.0	2018-07-18 21:44:41.031	info	States connected to redis: /var/run/redis/redis.sock
```

The message with just `undefined` makes me actually suspicious that there still might be an issue.

**Comment by MeisterTR** [comment]
the undefiend is just a rest of testing, if you install from git, there shoud be logged "DB510". bute i tested the 2.2.2 with an different id and it works. There is no big different to the 2.1.X.

**Comment by colinfrei** [comment]
Going to hijack this issue a bit - I have product_id 33. How do you decide what to map it to (DB510 vs DB504)?

**Comment by MeisterTR** [comment]
There is now a new fw for the m Modell with cloud connect. 504 is for m Modell and 510 for s. At Beginn I though m and s Modell only have on Id eg 33=s 35=m.. That was a mistake.. So I try to get the Modell out of the serial number.. If that does also not work I will place a selection box in the Config for the m Modells..

**Comment by SchimmerMediaHD** [comment]
Thank you very much MeisterTR for your Work, today i did realise the first time that it dont work anymore with my WORX Landroid S. i try to update from Git und hope it works, when not i just wait for your next update. If i can help you, please let me know. Best wishes :)

**Comment by martinschm** [comment]
I have the message: product_id: 37 Plese make an issue on git with this product id, its a S500i, the orange version from Hornbach

**Comment by ConfusedTA** [comment]
product_id: 26 Plese make an issue on git with this product id

Landroid S WR110MI

Strangely it worked on the first launch after adding the mower, but subsequent starts now give this message.

**Comment by MeisterTR** [comment]
This is just a notice, the adapter works anyway correct for s Modells

**Comment by ConfusedTA** [comment]
I'm using it via https://github.com/weweave/landroid-bridge and now I'm receiving this message, I don't get any details of the mower in that - but I did the very first time I added the mower to my account... :) As per https://github.com/weweave/landroid-bridge/issues/22 he's asked that it be noted here :)

**Comment by MeisterTR** [comment]
2.5.4 @ConfusedTA plese change to mqttCloud.js
