### ISSUE TITLE
ERROR: 	: message handler implemented, but messagebox not enabled. Define common.messagebox in io-package.json for adapter or delete message handler.

### ISSUE THREAD

**Issue by Lueghi** [MeisterTR/ioBroker.landroid-s#31]
Nach dem Start des Adapters kommt in Abständen immer wieder die o.g. Meldung. Nach meinen Recherchen liegt das wohl an einer fehlenden Anpassung des Adapters an die aktuelle jscontroller. Der Fehler ist wohl schon länger bekannt aber ich habe hierzu noch kein Issue gefunden ....

**Comment by MeisterTR** [comment]
Please change to the actual adapter iobroker.worx
