### ISSUE TITLE
Break out Worx API into its own package

### ISSUE THREAD

**Issue by riker09** [MeisterTR/ioBroker.landroid-s#34]
Hello, fellow smarthome user here. I have used your landroid bridge in the past to read the statistical data from my Landroid-S and integrate it with my Home Assistant. Thank you for your great work. However, Worx must have changed something in their API and now the Docker images that are based off of this repository, eg. https://github.com/virtualzone/landroid-bridge are not working anymore. I was wondering if it is possible to use the new adapter (https://github.com/iobroker-community-adapters/ioBroker.worx)?

I admit that I only invested very little time in trying to do so and now I wanted to check with you first to see if you have any helpful advise or insights? Maybe this was done by someone already and I was simple not able to find it? Any help will be greatly appreciated.

**Comment by MeisterTR** [comment]
gefixed

**Comment by riker09** [comment]
Ich danke vielmals, das hat mir eine mehrstündige Einarbeitung und Programmierodyssee erspart. :slightly_smiling_face:
