### ISSUE TITLE
Sending mqtt command not successful

### ISSUE THREAD

**Issue by quixony** [MeisterTR/ioBroker.landroid-s#35]
It is not possible to send an mqtt command to the broker. I use landroid-bridge, with pre-selected mower in config. Whenever I try to perform any command TO the broker / robot nothing happens. 
After some debugging I came to the point that the topic can not be generated as expected in
mqttCloud.js: line 169. 
I added the generated topic to the debug ouput and it showed: _Sending message: {"cmd":1} to topic: undefined/[MAC]/commandIn._ 
It seems the this.mqtt_topic_prefix does not exist. 

As a quick workaround I adjusted the function as follows using the transmitted commandIn topic: 
```
mqttCloud.prototype.sendMessage = function (message) {
    var self = this
    //var topicIn = self.mqtt_topic_prefix + "/" + this.macAddress + '/commandIn';
    this.adapter.log.debug('Sending Message: ' + message + ' to topic: ' + this.mqtt_command_in);
    //var sends = '{"cmd":3}';
    this.device.publish(self.mqtt_command_in, message);
};
```

But I think is not that flexible as it was intended to be.

**Comment by philippsandhaus** [comment]
https://github.com/MeisterTR/ioBroker.landroid-s/pull/36 fixes this
