### ISSUE TITLE
landroid-s.0	... warn	product_id: 24 Plese make an issue on git with this product id

### ISSUE THREAD

**Issue by allcoolusernamesaregone** [MeisterTR/ioBroker.landroid-s#4]
Mache ich doch gern ;)
Vermutlich unbekannte S Variante? Es ist der Worx WR105SI Landroid S500i 
EAN 6924328307518
z.B. https://www.ebay.de/itm/WORX-WR105SI-1-Landroid-S500I-Maehroboter-/263572100549

**Comment by MeisterTR** [comment]
thanks added the id
